export const PHOTO_SEND_REQUEST = 'PHOTO_SEND_REQUEST';
export const PHOTO_ADD_CHANGED_SUCCESSFULLY = 'PHOTO_ADD_CHANGED_SUCCESSFULLY';
export const PHOTO_DELETE_SUCCESSFULLY = 'PHOTO_DELETE_SUCCESSFULLY';

export const USER_CHANGED_SUCCESSFULLY = 'USER_CHANGED_SUCCESSFULLY';
export const USER_SEND_REQUEST = 'USER_SEND_REQUEST';